version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: projetoanime_db
    restart: always
    environment:
      MYSQL_DATABASE: projetoanime
      MYSQL_USER: animeuser
      MYSQL_PASSWORD: animepass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: python:3.11-slim
    container_name: projetoanime_web
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=projetoanime.settings
      - DB_HOST=db
      - DB_NAME=projetoanime
      - DB_USER=animeuser
      - DB_PASSWORD=animepass
    depends_on:
      - db

volumes:
  db_data:
